name: osmnx-examples
channels:
  - conda-forge
dependencies:
  - black
  - descartes
  - flake8
  - isort
  - jupyterlab
  - nbqa
  - osmnx=1.2.3
  - pillow
  - python=3.10.*
  - python-igraph
  - Shapely>=1.8,<2.0
